// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreatsFlavors.Models;

#nullable disable

namespace TreatsFlavors.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230814064856_InitialIdentity")]
    partial class InitialIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TreatsFlavors.Models.Flavor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Flavors");
                });

            modelBuilder.Entity("TreatsFlavors.Models.Treat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Treats");
                });

            modelBuilder.Entity("TreatsFlavors.Models.TreatFlavor", b =>
                {
                    b.Property<int>("TreatId")
                        .HasColumnType("int");

                    b.Property<int>("FlavorId")
                        .HasColumnType("int");

                    b.HasKey("TreatId", "FlavorId");

                    b.HasIndex("FlavorId");

                    b.ToTable("TreatFlavors");
                });

            modelBuilder.Entity("TreatsFlavors.Models.TreatFlavor", b =>
                {
                    b.HasOne("TreatsFlavors.Models.Flavor", "Flavor")
                        .WithMany("TreatFlavors")
                        .HasForeignKey("FlavorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreatsFlavors.Models.Treat", "Treat")
                        .WithMany("TreatFlavors")
                        .HasForeignKey("TreatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flavor");

                    b.Navigation("Treat");
                });

            modelBuilder.Entity("TreatsFlavors.Models.Flavor", b =>
                {
                    b.Navigation("TreatFlavors");
                });

            modelBuilder.Entity("TreatsFlavors.Models.Treat", b =>
                {
                    b.Navigation("TreatFlavors");
                });
#pragma warning restore 612, 618
        }
    }
}
